### ISSUE TITLE
Нужно бы зарелизить гем без Gemfile.lock

### ISSUE THREAD

**Issue by Nakilon** [gtproger/morse#15]
Потому что https://stackoverflow.com/a/4151540/322020

И потому что в зависимостях есть проблемный гем https://github.com/krisleech/wisper/issues/183 который автором заброшен, а форк подключить лок не позволит.

**Comment by Nakilon** [comment]
И почему Ruby 2.7? 2.4 не подойдет?

**Comment by Nakilon** [comment]
И еще одна вещь, которая может вызвать трудности у людей -- с `:ru` возвращается строка с `.encoding="utf-8"`, а без `:ru` -- `"ASCII"`. Было бы неплохо к обоим вариантам применять `.encode("utf-8")` в конце.

**Comment by dionixs** [comment]
Спасибо, исправил. А так же добавил поддержку руби начиная с версии 2.4.
